import { Prisma } from "@/generated/prisma/client";

export type SlackUserWithPrograms = Prisma.SlackUserGetPayload<{
  include: { programs: true };
}>;

export type UserWithSlackUser = Prisma.UserGetPayload<{
  include: { slackUser: true };
}>;

export type ProgramWithAssignees = Prisma.ProgramGetPayload<{
  include: {
    assignedUsers: {
      include: {
        users: {
          include: {
            programsOrganizing: true;
          };
        };
      };
    };
    usersOrganizing: true;
    tags: true;
  };
}>;

type TicketPayload = Prisma.TicketGetPayload<{
  include: {
    replies: {
      include: {
        slackUser: {
          include: {
            programs: true;
          };
        };
      };
    };
    slackUser: true;
    assignees: true;
    program: {
      include: {
        tags: true
      }
    };
    tag: true
  };
}>;

type TicketDetailed = Prisma.TicketGetPayload<{
  include: {
    slackUser: true;
    assignees: true;
    program: true;
    resolver: true;
    firstResponseUser: true;
    tag: true,
    _count: {
      select: {
        replies: true;
      };
    };
  };
}>;

export type BacklogStatus = {
  status: "unqueued" | "pending" | "failed" | "success" | "stopped";
  job?: BacklogJob;
};

export type BacklogJob = {
  programId: string;
  actorId: string;
  startDate: Date;
  backlogFrom: Date;
  backlogTo: Date;
  finishDate?: Date;
  error?: string;
  ts: {
    start: string;
    current: string;
    end: string;
  };
};
//this part was mostly generated by Claude Code
export type ReplyWithResolver = TicketPayload["replies"][number] & {
  resolver?: SlackUserWithPrograms | null;
  reopener?: SlackUserWithPrograms | null;
};

export type TicketWithReplies = Omit<TicketPayload, "replies"> & {
  replies: ReplyWithResolver[];
};

export type ProgramTicketsResponse = {
  tickets: TicketDetailed[];
  total: number;
};

export type UserWithAssignedCount = Prisma.SlackUserGetPayload<{
  include: {
    _count: {
      select: {
        assignedTickets: true;
      };
    };
  };
}>;
export type ProgramStatistics = {
  total: number;
  open: number;
  assigned: number;
  assignedToMe: number;
  resolved: number;
  usersTicketCount: UserWithAssignedCount[];
};

// the below type was generated by Claude Code
export type AnswerActivity = {
  // Average number of tickets answered on a given weekday (Sun-Sat).
  byWeekday: { day: string; average: number }[];
  // Average number of tickets answered during a given hour of the day (0-23).
  byHour: { hour: string; average: number }[];
};

export type HangTime = {
  time: number;
};
export type ResolveTime = {
  time: number;
};

export type RouteError = {
  info: {
    status: "Unauthorized" | "Unauthenticated" | "Not found";
  };
  status: number;
};
export type GlobalStats = {
  programs: number;
  tickets: number;
  replies: number;
  helpers: number;
  registered: number;
  slackUsers: number;
};
export type ProgramWithCount = Prisma.ProgramGetPayload<{
  include: {
    _count: {
      select: {
        tickets: true;
        assignedUsers: true;
      };
    };
  };
}>;
export type SlackUserDetailed = Prisma.SlackUserGetPayload<{
  include: {
    programs: true;
    createdTickets: {
      include: {
        program: true;
        assignees: true;
        resolver: true;
        firstResponseUser: true;
      };
    };
    resolvedTickets: {
      include: {
        program: true;
        assignees: true;
        resolver: true;
        firstResponseUser: true;
      };
    };
    assignedTickets: {
      include: {
        program: true;
        assignees: true;
        resolver: true;
        firstResponseUser: true;
      };
    };
    _count: {
      select: {
        programs: true;
        createdTickets: true;
        resolvedTickets: true;
        assignedTickets: true;
        users: true;
      };
    };
  };
}>;
export type TicketWithAssigneesAndProgram = Prisma.TicketGetPayload<{
  include: {
    program: true;
    assignees: true;
    resolver: true;
    firstResponseUser: true;
  };
}>;

export type SlackUserWithStats = Prisma.SlackUserGetPayload<{
  include: {
    programs: true;
    _count: {
      select: {
        programs: true;
        createdTickets: true;
        resolvedTickets: true;
        assignedTickets: true;
        users: true;
      };
    };
  };
}>;
export type SlackUserApiResponse = {
  users: SlackUserWithStats[];
  total: number;
};
