import { Prisma } from "@/generated/prisma/client";

export type SlackUserWithPrograms = Prisma.SlackUserGetPayload<{
  include: { programs: true };
}>;

export type UserWithSlackUser = Prisma.UserGetPayload<{
  include: { slackUser: true };
}>;

export type ProgramWithAssignees = Prisma.ProgramGetPayload<{
  include: {
    assignedUsers: {
      include: {
        users: {
          include: {
            programsOrganizing: true;
          };
        };
      };
    },
    usersOrganizing: true
  };
}>;

type TicketPayload = Prisma.TicketGetPayload<{
  include: {
    replies: {
      include: {
        slackUser: {
          include: {
            programs: true;
          };
        };
      };
    };
    slackUser: true;
    assignees: true;
    program: true;
  };
}>;

export type BacklogStatus = {
  status: "unqueued" | "pending" | "failed" | "success" | "stopped";
  job?: BacklogJob;
};

export type BacklogJob = {
  programId: string;
  actorId: string;
  startDate: Date;
  backlogFrom: Date;
  backlogTo: Date;
  finishDate?: Date;
  error?: string;
  ts: {
    start: string,
    current: string,
    end: string
  }
};
//this part was mostly generated by Claude Code
export type ReplyWithResolver = TicketPayload["replies"][number] & {
  resolver?: SlackUserWithPrograms | null;
  reopener?: SlackUserWithPrograms | null;
};

export type TicketWithReplies = Omit<TicketPayload, "replies"> & {
  replies: ReplyWithResolver[];

};

export type ProgramStatistics = {
  total: number;
  open: number;
  assigned: number;
  assignedToMe: number;
  resolved: number;
};

export type Leaderboard = {
  id: string;
  username: string;
  _count: {
    assignedTickets: number;
  };
}[];

export type HangTime = {
  time: number
}
export type ResolveTime = {
  time: number
}

export type RouteError = {
  info: {
    status: "Unauthorized" | "Unauthenticated" | "Not found"
  },
  status: number
}
export type GlobalStats = {
  programs: number;
  tickets: number;
  replies: number;
  helpers: number;
  registered: number;
  slackUsers: number;
}
export type ProgramWithCount = Prisma.ProgramGetPayload<{
  include: {
    _count: {
      select: {
        tickets: true,
        assignedUsers: true
      }
    }
  }
}>