import { Prisma } from "@/generated/prisma/client";

export type SlackUserWithPrograms = Prisma.SlackUserGetPayload<{
  include: { programs: true };
}>;

export type UserWithSlackUser = Prisma.UserGetPayload<{
  include: { slackUser: true };
}>;

export type ProgramWithAssignees = Prisma.ProgramGetPayload<{
  include: {
    assignedUsers: {
      include: {
        users: {
          include: {
            programsOrganizing: true;
          };
        };
      };
    };
  };
}>;

type TicketPayload = Prisma.TicketGetPayload<{
  include: {
    replies: {
      include: {
        slackUser: {
          include: {
            programs: true;
          };
        };
      };
    };
    slackUser: true;
    assignees: true;
    program: true;
  };
}>;

export type BacklogStatus = {
  status: "unqueued" | "pending" | "failed" | "success" | "stopped";
  job?: BacklogJob;
};

export type BacklogJob = {
  programId: string;
  actorId: string;
  startDate: Date;
  backlogFrom: Date;
  backlogTo: Date;
  finishDate?: Date;
  error?: string;
};
//this part was mostly generated by Claude Code
export type ReplyWithResolver = TicketPayload["replies"][number] & {
  resolver?: SlackUserWithPrograms | null;
  reopener?: SlackUserWithPrograms | null;
};

export type TicketWithReplies = Omit<TicketPayload, "replies"> & {
  replies: ReplyWithResolver[];
};

export type ProgramStatistics = {
  total: number;
  open: number;
  assigned: number;
  assignedToMe: number;
  resolved: number;
};
