import { prisma } from "@/app/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import { type NextRequest } from "next/server";

export async function GET(
  req: NextRequest,
  ctx: RouteContext<"/api/programs/[programId]">,
) {
  const { programId } = await ctx.params;
  const params = req.nextUrl.searchParams; //todo: searching stuff
  console.log(params);
  const searchTerm = params.get("searchTerm");
  const assigneeIds = params.get("assigneeIds")?.split(",");
  const statuses = params.get("statuses")?.split(",").map(Number) as number[];
  // this part was generated by Claude
  const filters: Prisma.TicketWhereInput[] = [];
  if (searchTerm && searchTerm.length > 0) {
    filters.push({ message: { contains: searchTerm, mode: "insensitive" } });
  }
  if (assigneeIds && assigneeIds[0].length > 0) {
    filters.push({ assignees: { some: { id: { in: assigneeIds } } } });
  }
  console.log(assigneeIds)
  if (statuses?.length > 0) {
    filters.push({ status: { in: statuses } });
  }

  const ticket = await prisma.ticket.findMany({
    where: {
      programId,
      ...(filters.length ? { AND: filters } : {}),
    }, // end of Claude code
    include: {
      replies: {
        include: {
          slackUser: true,
        },
      },
      slackUser: true,
      assignees: true,
    },
  });
  if (!ticket)
    return new Response(JSON.stringify({ status: "Not found" }), {
      status: 404,
    });
  return new Response(JSON.stringify(ticket));
}
