import { ITEMS_PER_PAGE } from "@/app/lib/constants";
import { getUserAuthStatus } from "@/app/lib/data";
import { prisma } from "@/app/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import { type NextRequest } from "next/server";

export async function GET(
  req: NextRequest,
  ctx: RouteContext<"/api/programs/[programId]">,
) {
  const authStatus = await getUserAuthStatus();
  if (authStatus.status === "unauthenticated") {
    return new Response(JSON.stringify({ status: "Unauthenticated" }), {
      status: 401,
    });
  }
  const { programId } = await ctx.params;
  const id = programId !== "all" ? programId : undefined;
  const params = req.nextUrl.searchParams; 
  console.log(params);
  const searchTerm = params.get("searchTerm");
  const assigneeIds = params.get("assigneeIds")?.split(",");
  const statuses = params.get("statuses")?.split(",").map(Number) as number[];
  const order = params.get("order") ?? "dateCreated.asc";
  const page = params.get("page");

  const field = order.split(".")[0]
  const direction = order.split(".")[1]

  // coded by claude
  const dir: Prisma.SortOrder = direction === "desc" ? "desc" : "asc";

  const orderByMap: Record<string, Prisma.TicketOrderByWithRelationInput> = {
    program: { program: { name: dir } },
    dateCreated: { dateCreated: dir },
    status: { status: dir },
    frt: { responseTime: dir },
    resolveTime: { resolveTime: dir },
  };

  // the field-based sort only applies to the global search (programId === "all");
  // individual program pages still pass a bare direction and sort by dateCreated.
  const orderBy: Prisma.TicketOrderByWithRelationInput =
    id === undefined
      ? (orderByMap[field] ?? { dateCreated: "asc" })
      : { dateCreated: order as "asc" | "desc" };
  // end of claude code

  // this part was generated by Claude
  const filters: Prisma.TicketWhereInput[] = [];
  if (searchTerm && searchTerm.length > 0) {
    filters.push({ message: { contains: searchTerm, mode: "insensitive" } });
  }
  if (assigneeIds && assigneeIds[0].length > 0) {
    filters.push({ assignees: { some: { id: { in: assigneeIds } } } });
  }
  console.log(assigneeIds);
  if (statuses?.length > 0) {
    filters.push({ status: { in: statuses } });
  }

  console.log(filters);

  const tickets = await prisma.ticket.findMany({
    where: {
      programId: id,
      ...(filters.length ? { AND: filters } : {}),
    }, // end of Claude code
    include: {
      slackUser: true,
      assignees: true,
      program: true,
      resolver: true,
      firstResponseUser: true,
      _count: {
        select: {
          replies: true,
        },
      },
    },
    orderBy,
    skip: ((Number(page) || 1) - 1) * ITEMS_PER_PAGE,
    take: 20,
  });
  const count = await prisma.ticket.count({
    where: {
      programId: id,
      ...(filters.length ? { AND: filters } : {}),
    },
  });
  if (!tickets)
    return new Response(JSON.stringify({ status: "Not found" }), {
      status: 404,
    });
  return new Response(
    JSON.stringify({
      tickets: tickets,
      total: count,
    }),
  );
}
