import { ITEMS_PER_PAGE } from "@/app/lib/constants";
import { getUserAuthStatus } from "@/app/lib/data";
import { prisma } from "@/app/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import { type NextRequest } from "next/server";

export async function GET(
  req: NextRequest,
  ctx: RouteContext<"/api/programs/[programId]">,
) {
  const authStatus = await getUserAuthStatus();
  if (authStatus.status === "unauthenticated") {
    return new Response(JSON.stringify({ status: "Unauthenticated" }), {
      status: 401,
    });
  }
  const { programId } = await ctx.params;
  const params = req.nextUrl.searchParams; //todo: searching stuff
  console.log(params);
  const searchTerm = params.get("searchTerm");
  const assigneeIds = params.get("assigneeIds")?.split(",");
  const statuses = params.get("statuses")?.split(",").map(Number) as number[];
  const order = params.get("order");
  const page = params.get("page");
  // this part was generated by Claude
  const filters: Prisma.TicketWhereInput[] = [];
  if (searchTerm && searchTerm.length > 0) {
    filters.push({ message: { contains: searchTerm, mode: "insensitive" } });
  }
  if (assigneeIds && assigneeIds[0].length > 0) {
    filters.push({ assignees: { some: { id: { in: assigneeIds } } } });
  }
  console.log(assigneeIds);
  if (statuses?.length > 0) {
    filters.push({ status: { in: statuses } });
  }

  console.log(filters);

  const tickets = await prisma.ticket.findMany({
    where: {
      programId,
      ...(filters.length ? { AND: filters } : {}),
    }, // end of Claude code
    include: {
      replies: {
        include: {
          slackUser: true,
        },
      },
      slackUser: true,
      assignees: true,
    },
    orderBy: {
      dateCreated: order as "asc" | "desc",
    },
    skip: ((Number(page) || 1) - 1) * ITEMS_PER_PAGE,
    take: 20,
  });
  const count = await prisma.ticket.count({
    where: {
      programId,
      ...(filters.length ? { AND: filters } : {}),
    },
  });
  if (!tickets)
    return new Response(JSON.stringify({ status: "Not found" }), {
      status: 404,
    });
  return new Response(
    JSON.stringify({
      tickets: tickets,
      total: count,
    }),
  );
}
