import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import { Toast } from "@heroui/react";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ ticketId: string; programId: string }>;
}>) {
  const slugs = await params;
  return (
    <html
      lang="en"
      className={`${ibmPlexSans.className} h-full antialiased bg-gray-50 dark`}
    >
      <Toast.Provider placement="top" />
      <body className="h-full flex flex-col bg-background text-foreground">
        <div className="flex flex-col h-full">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
