import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import ProgramSelector from "./ui/program-selector";
import { Avatar, Button } from "@heroui/react";
import { LogInIcon } from "lucide-react";
import { auth } from "./lib/auth";
import { headers } from "next/headers";
import { prisma } from "./lib/prisma";
import { getUser } from "./lib/data";
import SignInButton from "./ui/sign-in-button";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(), // you need to pass the headers object.
  });
  let user;
  if (session?.user.id) user = await getUser(session?.user.id);
  console.log(session);

  return (
    <html
      lang="en"
      className={`${ibmPlexSans.className} h-full antialiased bg-gray-50 dark`}
    >
      <body className="h-full flex flex-col bg-background text-foreground">
        <div className="flex flex-col h-full">
          <div className="flex flex-row justify-between p-4 border-b border-accent-background">
            <div className="flex flex-row gap-4 items-center">
              <h2 className="text-lg">
                unified<b>help</b>
              </h2>
              <ProgramSelector />
            </div>
            <div className="flex flex-row gap-4 items-center">
              {!session?.user && <SignInButton />}
              {session && session.user && (
                <Avatar size="sm">
                  <Avatar.Image
                    src={`https://cachet.dunkirk.sh/users/${user?.slackUser?.id}/r`}
                    alt="Profile picture"
                  />
                  <Avatar.Fallback>
                    {user?.slackUser?.username.substring(0, 1)}
                  </Avatar.Fallback>
                </Avatar>
              )}
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
