import { type NextRequest } from "next/server";
import { getResolver } from "@/app/lib/tools";
import { getTicket, getUserAuthStatus } from "@/app/lib/data";

export async function GET(
  _req: NextRequest,
  ctx: RouteContext<"/api/ticket/[ticketId]">,
) {
  const authStatus = await getUserAuthStatus();
  if (authStatus.status === "unauthenticated") {
    return new Response(JSON.stringify({ status: "Unauthorized" }), {
      status: 401,
    });
  }
  const { ticketId } = await ctx.params;

  const ticket = await getTicket(ticketId);

  if (!ticket)
    return new Response(JSON.stringify({ status: "Not found" }), {
      status: 404,
    });

  // this part was mostly generated by Claude Code
  const replies = await Promise.all(
    ticket.replies.map(async (r) => {
      if (
        (r.slackUser.isBot &&
          r.message.includes(ticket.program.resolveKeyword)) ||
        (process.env["NEXT_PUBLIC_RESOLVER_USER_ID"] === r.slackUser.id &&
          r.message.includes("Marked as resolved"))
      ) {
        return { ...r, resolver: await getResolver(r.message) };
      }
      if (
        (r.slackUser.isBot ||
          process.env["NEXT_PUBLIC_RESOLVER_USER_ID"] === r.slackUser.id) &&
        r.message.includes("reopened")
      ) {
        return { ...r, reopener: await getResolver(r.message) };
      }
      return r;
    }),
  );

  return new Response(JSON.stringify({ ...ticket, replies }));
}
