import { prisma } from "@/app/lib/prisma";
import { type NextRequest } from "next/server";
import { getResolver } from "@/app/lib/tools";

export async function GET(
  _req: NextRequest,
  ctx: RouteContext<"/api/ticket/[ticketId]">,
) {
  const { ticketId } = await ctx.params;
  const ticket = await prisma.ticket.findUnique({
    where: {
      id: ticketId,
    },
    include: {
      replies: {
        include: {
          slackUser: {
            include: {
              programs: true,
            },
          },
        },
      },
      slackUser: true,
    },
  });
  if (!ticket)
    return new Response(JSON.stringify({ status: "Not found" }), {
      status: 404,
    });

  // this part was mostly generated by Claude Code
  const replies = await Promise.all(
    ticket.replies.map(async (r) => {
      if (r.slackUser.isBot && r.message.includes("marked as resolved")) {
        return { ...r, resolver: await getResolver(r.message) };
      }
      if (r.slackUser.isBot && r.message.includes("reopened")) {
        return { ...r, reopener: await getResolver(r.message) };
      }
      return r;
    }),
  );

  return new Response(JSON.stringify({ ...ticket, replies }));
}
